#ifndef DB_COMMAND_H
 #define DB_COMMAND_H

#include <db.h>

typedef enum db_read_command_e {
    DB_TECHNICIAN_READ_ID_COMMAND = 100, // MUST START > 0
    DB_TECHNICIAN_READ_NAME_COMMAND,
    DB_TECHNICIAN_READ_EMAIL_COMMAND,
    DB_TECHNICIAN_READ_PHONE_NUMBER_COMMAND,
    DB_TECHNICIAN_READ_RULES,
    DB_TECHNICIAN_READ_CREATED_AT,
    DB_TECHNICIAN_READ_VERSION,
    DB_CLIENT_READ_ID_COMMAND,
    DB_CLIENT_READ_TECHNICIAN_ID_COMMAND,
    DB_CLIENT_READ_CREATED_AT_COMMAND,
    DB_CLIENT_READ_CPF_COMMAND,
    DB_CLIENT_READ_NAME_COMMAND,
    DB_CLIENT_READ_ADDRESS_COMMAND,
    DB_CLIENT_READ_DISTRICT_CITY_COMMAND,
    DB_CLIENT_READ_EMAIL_COMMAND,
    DB_CLIENT_READ_PHONE_NUMBER_COMMAND,
    DB_CLIENT_READ_VERSION_COMMAND,
    DB_REPAIR_READ_CLIENT_ID,
    DB_REPAIR_READ_IS_BUDGET,
    DB_REPAIR_READ_DEVICE_PROBLEM,
    DB_REPAIR_READ_BRAND_MODEL,
    DB_REPAIR_READ_SERIAL_NUMBER,
    DB_REPAIR_READ_CLAIMED_DEFECT,
    DB_REPAIR_READ_OBSERVATION,
    DB_REPAIR_READ_MONETARY_TYPE,
    DB_REPAIR_READ_EXPECTED_BUDGET_DATE,
    DB_REPAIR_READ_EXPECTED_DELIVERY_DATE,
    DB_REPAIR_READ_LABOR_BUDGET,
    DB_REPAIR_READ_DELIVERY_DATE,
    DB_REPAIR_READ_WARRANTY,
    DB_SERVICE_READ_REPAIR_REQUEST_ID,
    DB_SERVICE_READ_QUANTITY,
    DB_SERVICE_READ_MONETARY_TYPE,
    DB_SERVICE_READ_UNITY_PRICE,
    DB_SERVICE_READ_DESCRIPTION
} DB_READ_ENUM_COMMAND;

typedef enum db_add_command_e {
    DB_TECHNICIAN_ADD_ID_COMMAND = 1, // MUST START > 0
    DB_TECHNICIAN_ADD_NAME_COMMAND,
    DB_TECHNICIAN_ADD_EMAIL_COMMAND,
    DB_TECHNICIAN_ADD_PHONE_NUMBER_COMMAND,
    DB_TECHNICIAN_ADD_RULES,
    DB_TECHNICIAN_ADD_CREATED_AT,
    DB_TECHNICIAN_ADD_VERSION,
    DB_CLIENT_ADD_ID_COMMAND,
    DB_CLIENT_ADD_TECHNICIAN_ID_COMMAND,
    DB_CLIENT_ADD_CREATED_AT_COMMAND,
    DB_CLIENT_ADD_CPF_COMMAND,
    DB_CLIENT_ADD_NAME_COMMAND,
    DB_CLIENT_ADD_ADDRESS_COMMAND,
    DB_CLIENT_ADD_DISTRICT_CITY_COMMAND,
    DB_CLIENT_ADD_EMAIL_COMMAND,
    DB_CLIENT_ADD_PHONE_NUMBER_COMMAND,
    DB_CLIENT_ADD_VERSION_COMMAND,
    DB_REPAIR_ADD_CLIENT_ID,
    DB_REPAIR_ADD_IS_BUDGET,
    DB_REPAIR_ADD_DEVICE_PROBLEM,
    DB_REPAIR_ADD_BRAND_MODEL,
    DB_REPAIR_ADD_SERIAL_NUMBER,
    DB_REPAIR_ADD_CLAIMED_DEFECT,
    DB_REPAIR_ADD_OBSERVATION,
    DB_REPAIR_ADD_MONETARY_TYPE,
    DB_REPAIR_ADD_EXPECTED_BUDGET_DATE,
    DB_REPAIR_ADD_EXPECTED_DELIVERY_DATE,
    DB_REPAIR_ADD_LABOR_BUDGET,
    DB_REPAIR_ADD_DELIVERY_DATE,
    DB_REPAIR_ADD_WARRANTY,
    DB_SERVICE_ADD_REPAIR_REQUEST_ID,
    DB_SERVICE_ADD_QUANTITY,
    DB_SERVICE_ADD_MONETARY_TYPE,
    DB_SERVICE_ADD_UNITY_PRICE,
    DB_SERVICE_ADD_DESCRIPTION
} DB_ADD_ENUM_COMMAND;

typedef enum db_update_command_e {
    DB_TECHNICIAN_UPDATE_ID_COMMAND = 50,  // MUST START > 0
    DB_TECHNICIAN_UPDATE_NAME_COMMAND,
    DB_TECHNICIAN_UPDATE_EMAIL_COMMAND,
    DB_TECHNICIAN_UPDATE_PHONE_NUMBER_COMMAND,
    DB_TECHNICIAN_UPDATE_RULES,
    DB_TECHNICIAN_UPDATE_CREATED_AT,
    DB_TECHNICIAN_UPDATE_VERSION,
    DB_CLIENT_UPDATE_ID_COMMAND,
    DB_CLIENT_UPDATE_TECHNICIAN_ID_COMMAND,
    DB_CLIENT_UPDATE_CREATED_AT_COMMAND,
    DB_CLIENT_UPDATE_CPF_COMMAND,
    DB_CLIENT_UPDATE_NAME_COMMAND,
    DB_CLIENT_UPDATE_ADDRESS_COMMAND,
    DB_CLIENT_UPDATE_DISTRICT_CITY_COMMAND,
    DB_CLIENT_UPDATE_EMAIL_COMMAND,
    DB_CLIENT_UPDATE_PHONE_NUMBER_COMMAND,
    DB_CLIENT_UPDATE_VERSION_COMMAND,
    DB_REPAIR_UPDATE_CLIENT_ID,
    DB_REPAIR_UPDATE_IS_BUDGET,
    DB_REPAIR_UPDATE_DEVICE_PROBLEM,
    DB_REPAIR_UPDATE_BRAND_MODEL,
    DB_REPAIR_UPDATE_SERIAL_NUMBER,
    DB_REPAIR_UPDATE_CLAIMED_DEFECT,
    DB_REPAIR_UPDATE_OBSERVATION,
    DB_REPAIR_UPDATE_MONETARY_TYPE,
    DB_REPAIR_UPDATE_EXPECTED_BUDGET_DATE,
    DB_REPAIR_UPDATE_EXPECTED_DELIVERY_DATE,
    DB_REPAIR_UPDATE_LABOR_BUDGET,
    DB_REPAIR_UPDATE_DELIVERY_DATE,
    DB_REPAIR_UPDATE_WARRANTY,
    DB_SERVICE_UPDATE_REPAIR_REQUEST_ID,
    DB_SERVICE_UPDATE_QUANTITY,
    DB_SERVICE_UPDATE_MONETARY_TYPE,
    DB_SERVICE_UPDATE_UNITY_PRICE,
    DB_SERVICE_UPDATE_DESCRIPTION
} DB_UPDATE_ENUM_COMMAND;

int technician_add(TECHNICIAN_DATA *, ...);

#define TECHNICIAN_EXECUTE_ADD(val, ...) \
    technician_add(val, __VA_ARGS__, 0, NULL);

  #define TECHNICIAN_ADD_ID(v) DB_TECHNICIAN_ADD_ID_COMMAND, (size_t)v
  #define TECHNICIAN_ADD_NAME(v) DB_TECHNICIAN_ADD_NAME_COMMAND, v
  #define TECHNICIAN_ADD_EMAIL(v) DB_TECHNICIAN_ADD_EMAIL_COMMAND, v
  #define TECHNICIAN_ADD_PHONE_NUMBER(v) DB_TECHNICIAN_ADD_PHONE_NUMBER_COMMAND, v
  #define TECHNICIAN_ADD_RULES(v) DB_TECHNICIAN_ADD_RULES, (size_t)v
  #define TECHNICIAN_ADD_CREATED_AT(v) DB_TECHNICIAN_ADD_CREATED_AT, (size_t)v
  #define TECHNICIAN_ADD_VERSION(v) DB_TECHNICIAN_ADD_VERSION, (size_t)v

int technician_update(TECHNICIAN_DATA *, ...);

#define TECHNICIAN_EXECUTE_UPDATE(val, ...) \
    technician_update(val, __VA_ARGS__, 0, NULL);

  #define TECHNICIAN_UPDATE_NAME(v) DB_TECHNICIAN_UPDATE_NAME_COMMAND, v
  #define TECHNICIAN_UPDATE_EMAIL(v) DB_TECHNICIAN_UPDATE_EMAIL_COMMAND, v
  #define TECHNICIAN_UPDATE_PHONE_NUMBER(v) DB_TECHNICIAN_UPDATE_PHONE_NUMBER_COMMAND, v
  #define TECHNICIAN_UPDATE_RULES(v) DB_TECHNICIAN_UPDATE_RULES, v

int technician_read(TECHNICIAN_DATA *, ...);

#define TECHNICIAN_EXECUTE_READ(val, ...) \
    technician_read(val, __VA_ARGS__, 0, NULL);

  #define TECHNICIAN_READ_ID(v) DB_TECHNICIAN_READ_ID_COMMAND, (size_t)v
  #define TECHNICIAN_READ_NAME(v) DB_TECHNICIAN_READ_NAME_COMMAND, v
  #define TECHNICIAN_READ_EMAIL(v) DB_TECHNICIAN_READ_EMAIL_COMMAND, v
  #define TECHNICIAN_READ_PHONE_NUMBER(v) DB_TECHNICIAN_READ_PHONE_NUMBER_COMMAND, v
  #define TECHNICIAN_READ_RULES(v) DB_TECHNICIAN_READ_RULES, (size_t)v
  #define TECHNICIAN_READ_CREATED_AT(v) DB_TECHNICIAN_READ_CREATED_AT, (size_t)v
  #define TECHNICIAN_READ_VERSION(v) DB_TECHNICIAN_READ_VERSION, (size_t)v

void technician_delete(TECHNICIAN_DATA *);

int client_add(CLIENT_DATA *, ...);

#define CLIENT_EXECUTE_ADD(val, ...) \
  client_add(val, __VA_ARGS__, 0, NULL);

  #define CLIENT_ADD_ID(v) DB_CLIENT_ADD_ID_COMMAND, (size_t)v
  #define CLIENT_ADD_TECHNICIAN_ID(v) DB_CLIENT_ADD_TECHNICIAN_ID_COMMAND, (size_t)v
  #define CLIENT_ADD_CREATED_AT(v) DB_CLIENT_ADD_CREATED_AT_COMMAND, (size_t)v
  #define CLIENT_ADD_CPF(v) DB_CLIENT_ADD_CPF_COMMAND, v
  #define CLIENT_ADD_NAME(v) DB_CLIENT_ADD_NAME_COMMAND, v
  #define CLIENT_ADD_ADDRESS(v) DB_CLIENT_ADD_ADDRESS_COMMAND, v
  #define CLIENT_ADD_DISTRICT_CITY(v) DB_CLIENT_ADD_DISTRICT_CITY_COMMAND, v
  #define CLIENT_ADD_EMAIL(v) DB_CLIENT_ADD_EMAIL_COMMAND, v
  #define CLIENT_ADD_PHONE_NUMBER(v) DB_CLIENT_ADD_PHONE_NUMBER_COMMAND, v
  #define CLIENT_ADD_VERSION(v) DB_CLIENT_ADD_VERSION_COMMAND, (size_t)v

int client_read(CLIENT_DATA *, ...);
#define CLIENT_EXECUTE_READ(val, ...) \
  client_read(val, __VA_ARGS__, 0, NULL);

  #define CLIENT_READ_ID(v) DB_CLIENT_READ_ID_COMMAND, (size_t)v
  #define CLIENT_READ_TECHNICIAN_ID(v) DB_CLIENT_READ_TECHNICIAN_ID_COMMAND, (size_t)v
  #define CLIENT_READ_CREATED_AT(v) DB_CLIENT_READ_CREATED_AT_COMMAND, (size_t)v
  #define CLIENT_READ_CPF(v) DB_CLIENT_READ_CPF_COMMAND, v
  #define CLIENT_READ_NAME(v) DB_CLIENT_READ_NAME_COMMAND, v
  #define CLIENT_READ_ADDRESS(v) DB_CLIENT_READ_ADDRESS_COMMAND, v
  #define CLIENT_READ_DISTRICT_CITY(v) DB_CLIENT_READ_DISTRICT_CITY_COMMAND, v
  #define CLIENT_READ_EMAIL(v) DB_CLIENT_READ_EMAIL_COMMAND, v
  #define CLIENT_READ_PHONE_NUMBER(v) DB_CLIENT_READ_PHONE_NUMBER_COMMAND, v
  #define CLIENT_READ_VERSION(v) DB_CLIENT_READ_VERSION_COMMAND, (size_t)v

int client_update(CLIENT_DATA *client_data, ...);

#define CLIENT_EXECUTE_UPDATE(val, ...) \
  client_update(val, __VA_ARGS__, 0, NULL);

  #define CLIENT_UPDATE_TECHNICIAN_ID(v) DB_CLIENT_UPDATE_TECHNICIAN_ID_COMMAND, (size_t)v
  #define CLIENT_UPDATE_CPF(v) DB_CLIENT_UPDATE_CPF_COMMAND, v
  #define CLIENT_UPDATE_NAME(v) DB_CLIENT_UPDATE_NAME_COMMAND, v
  #define CLIENT_UPDATE_UPDATERESS(v) DB_CLIENT_UPDATE_UPDATERESS_COMMAND, v
  #define CLIENT_UPDATE_DISTRICT_CITY(v) DB_CLIENT_UPDATE_DISTRICT_CITY_COMMAND, v
  #define CLIENT_UPDATE_EMAIL(v) DB_CLIENT_UPDATE_EMAIL_COMMAND, v
  #define CLIENT_UPDATE_PHONE_NUMBER(v) DB_CLIENT_UPDATE_PHONE_NUMBER_COMMAND, v

int repair_add(REPAIR *, ...);

#define REPAIR_EXECUTE_ADD(val, ...) \
  repair_add(val, __VA_ARGS__, 0, NULL);

  #define REPAIR_ADD_CLIENT_ID(v) DB_REPAIR_ADD_CLIENT_ID, (size_t)v
  #define REPAIR_ADD_IS_BUDGET(v) DB_REPAIR_ADD_IS_BUDGET, v
  #define REPAIR_ADD_DEVICE_PROBLEM(v) DB_REPAIR_ADD_DEVICE_PROBLEM, v
  #define REPAIR_ADD_BRAND_MODEL(v) DB_REPAIR_ADD_BRAND_MODEL , v
  #define REPAIR_ADD_SERIAL_NUMBER(v) DB_REPAIR_ADD_SERIAL_NUMBER, v
  #define REPAIR_ADD_CLAIMED_DEFECT(v) DB_REPAIR_ADD_CLAIMED_DEFECT, v
  #define REPAIR_ADD_OBSERVATION(v) DB_REPAIR_ADD_OBSERVATION, v
  #define REPAIR_ADD_MONETARY_TYPE(v) DB_REPAIR_ADD_MONETARY_TYPE, v
  #define REPAIR_ADD_EXPECTED_BUDGET_DATE(v) DB_REPAIR_ADD_EXPECTED_BUDGET_DATE, v
  #define REPAIR_ADD_EXPECTED_DELIVERY_DATE(v) DB_REPAIR_ADD_EXPECTED_DELIVERY_DATE, v
  #define REPAIR_ADD_LABOR_BUDGET(v) DB_REPAIR_ADD_LABOR_BUDGET, v
  #define REPAIR_ADD_DELIVERY_DATE(v) DB_REPAIR_ADD_DELIVERY_DATE, v
  #define REPAIR_ADD_WARRANTY(v) DB_REPAIR_ADD_WARRANTY, v

int service_add(SERVICE *, ...);

#define SERVICE_EXECUTE_ADD(val, ...) \
  service_add(val, __VA_ARGS__, 0, NULL);

#define SERVICE_REPAIR_REQUEST_ID(v) DB_SERVICE_ADD_REPAIR_REQUEST_ID, (size_t)v
#define SERVICE_QUANTITY(v) DB_SERVICE_ADD_QUANTITY, v
#define SERVICE_MONETARY_TYPE(v) DB_SERVICE_ADD_MONETARY_TYPE, v
#define SERVICE_UNITY_PRICE(v) DB_SERVICE_ADD_UNITY_PRICE, v
#define SERVICE_DESCRIPTION(v) DB_SERVICE_ADD_DESCRIPTION, v

int repair_update(REPAIR *, ...);
void repair_delete(REPAIR *);

#endif