#ifndef DB_CONFIG_H
 #define DB_CONFIG_H

#define MIN_REPAIR_REQUESTS_INITIAL 16 // MIN request list element per client at init
#define MAX_REPAIR_REQUESTS_LIMIT 1024 // MAX request list element per client

_Static_assert(MIN_REPAIR_REQUESTS_INITIAL > 0, "MIN_REPAIR_REQUEST_INITIAL must be greater than 0");
_Static_assert(((MIN_REPAIR_REQUESTS_INITIAL & 1) == 0) && ((MAX_REPAIR_REQUESTS_LIMIT & 1) == 0), "MIN_REPAIR_REQUEST_INITIAL and MAX_REPAIR_REQUESTS_LIMIT must be multiple of 2");
_Static_assert(MAX_REPAIR_REQUESTS_LIMIT > MIN_REPAIR_REQUESTS_INITIAL, "Wrong REPAIR REQUEST boundaries");

#define MIN_SERVICE_REQUESTS_INITIAL MIN_REPAIR_REQUESTS_INITIAL
#define MAX_SERVICE_REQUESTS_LIMIT MAX_REPAIR_REQUESTS_LIMIT

_Static_assert(MIN_SERVICE_REQUESTS_INITIAL > 0, "MIN_SERVICE_REQUESTS_INITIAL must be greater than 0");
_Static_assert(((MIN_SERVICE_REQUESTS_INITIAL & 1) == 0) && ((MAX_SERVICE_REQUESTS_LIMIT & 1) == 0), "MIN_SERVICE_REQUESTS_INITIAL and MAX_SERVICE_REQUESTS_LIMIT must be multiple of 2");
_Static_assert(MAX_SERVICE_REQUESTS_LIMIT > MIN_SERVICE_REQUESTS_INITIAL, "Wrong SERVICE_REQUESTS boundaries");

#define MIN_CLIENT_DATA_REQUESTS_INITIAL MIN_REPAIR_REQUESTS_INITIAL
#define MAX_CLIENT_DATA_REQUESTS_LIMIT MAX_REPAIR_REQUESTS_LIMIT

_Static_assert(MIN_CLIENT_DATA_REQUESTS_INITIAL > 0, "MIN_CLIENT_DATA_REQUESTS_INITIAL must be greater than 0");
_Static_assert(((MIN_CLIENT_DATA_REQUESTS_INITIAL & 1) == 0) && ((MAX_CLIENT_DATA_REQUESTS_LIMIT & 1) == 0), "MIN_CLIENT_DATA_REQUESTS_INITIAL and MAX_CLIENT_DATA_REQUESTS_LIMIT must be multiple of 2");
_Static_assert(MAX_CLIENT_DATA_REQUESTS_LIMIT > MIN_CLIENT_DATA_REQUESTS_INITIAL, "Wrong CLIENT_DATA boundaries");

#define MIN_TECHNICIAN_DATA_REQUESTS_INITIAL MIN_REPAIR_REQUESTS_INITIAL
#define MAX_TECHNICIAN_DATA_REQUESTS_LIMIT MAX_REPAIR_REQUESTS_LIMIT

_Static_assert(MIN_TECHNICIAN_DATA_REQUESTS_INITIAL > 0, "MIN_TECHNICIAN_DATA_REQUESTS_INITIAL must be greater than 0");
_Static_assert(((MIN_TECHNICIAN_DATA_REQUESTS_INITIAL & 1) == 0) && ((MAX_TECHNICIAN_DATA_REQUESTS_LIMIT & 1) == 0), "MIN_TECHNICIAN_DATA_REQUESTS_INITIAL and MAX_TECHNICIAN_DATA_REQUESTS_LIMIT must be multiple of 2");
_Static_assert(MAX_TECHNICIAN_DATA_REQUESTS_LIMIT > MIN_TECHNICIAN_DATA_REQUESTS_INITIAL, "Wrong TECHNICIAN_DATA_REQUESTS boundaries");

#endif
