#ifndef DB_COMMAND_H
 #define DB_COMMAND_H

#include <db.h>

typedef enum db_add_command_e {
    DB_TECHNICIAN_ADD_NAME_COMMAND = 1, // MUST START > 0
    DB_TECHNICIAN_ADD_EMAIL_COMMAND,
    DB_TECHNICIAN_ADD_PHONE_NUMBER_COMMAND,
    DB_TECHNICIAN_ADD_RULES
} DB_ADD_ENUM_COMMAND;

int technician_add(TECHNICIAN_DATA *, ...);

#define TECHNICIAN_EXECUTE_ADD(val, ...) \
    technician_add(val, __VA_ARGS__, NULL, 0);

  #define TECHNICIAN_NAME(v) v, DB_TECHNICIAN_ADD_NAME_COMMAND
  #define TECHNICIAN_EMAIL(v) v, DB_TECHNICIAN_ADD_EMAIL_COMMAND
  #define TECHNICIAN_PHONE_NUMBER(v) v, DB_TECHNICIAN_ADD_PHONE_NUMBER_COMMAND
  #define TECHNICIAN_ADD_RULES(v) v, DB_TECHNICIAN_ADD_RULES

#endif